### ISSUE TITLE
Frontend Error after sending form

### ISSUE THREAD

**Issue by zzzooorrrx** [eliashaeussler/typo3-form-consent#58]
### TYPO3 version

11.5.10

### PHP version

8.1.5

### Extension version

0.5.1

### Composer mode

- [ ] I'm running TYPO3 in composer mode.

### Operating system

macOS 11.6.4

### Current behavior

After sending form error occurs in FE. her is the whole from error log:

```
Fri, 13 May 2022 16:07:14 +0200 [ALERT] request="2f5530301542a" component="TYPO3.CMS.Frontend.ContentObject.Exception.ProductionExceptionHandler": Huch, da ist ein Fehler aufgetreten :-( ! 20220513140713fd1b26ad- InvalidFileException: Resource paths must start with "EXT:", in file /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Utility/PathUtility.php:101 - {"exception":"TYPO3\\CMS\\Core\\Resource\\Exception\\InvalidFileException: Resource paths must start with \"EXT:\" in /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Utility/PathUtility.php:101\nStack trace:
#0 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/ViewHelpers/NormalizedUrlViewHelper.php(76): TYPO3\\CMS\\Core\\Utility\\PathUtility::getPublicResourceWebPath()
#1 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/ViewHelper/Traits/CompileWithContentArgumentAndRenderStatic.php(50): TYPO3\\CMS\\Core\\ViewHelpers\\NormalizedUrlViewHelper::renderStatic()
#2 [internal function]: TYPO3\\CMS\\Core\\ViewHelpers\\NormalizedUrlViewHelper->render()
#3 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(264): call_user_func()
#4 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(252): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->callRenderMethod()
#5 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperInvoker.php(79): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->initializeArgumentsAndRender()
#6 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/ViewHelperNode.php(150): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\ViewHelperInvoker->invoke()
#7 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/EscapingNode.php(43): TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\ViewHelperNode->evaluate()
#8 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/AbstractNode.php(56): TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\EscapingNode->evaluate()
#9 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/AbstractNode.php(36): TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\AbstractNode->evaluateChildNode()
#10 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(306): TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\AbstractNode->evaluateChildNodes()
#11 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/ViewHelpers/ThenViewHelper.php(35): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->renderChildren()
#12 [internal function]: TYPO3Fluid\\Fluid\\ViewHelpers\\ThenViewHelper->render()
#13 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(264): call_user_func()
#14 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(252): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->callRenderMethod()
#15 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperInvoker.php(79): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->initializeArgumentsAndRender()
#16 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/ViewHelperNode.php(150): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\ViewHelperInvoker->invoke()
#17 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractConditionViewHelper.php(164): TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\ViewHelperNode->evaluate()
#18 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractConditionViewHelper.php(60): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractConditionViewHelper->renderThenChild()
#19 [internal function]: TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractConditionViewHelper->render()
#20 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(264): call_user_func()
#21 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php(252): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->callRenderMethod()
#22 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/ViewHelper/ViewHelperInvoker.php(79): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractViewHelper->initializeArgumentsAndRender()
#23 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/ViewHelperNode.php(150): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\ViewHelperInvoker->invoke()
#24 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/AbstractNode.php(56): TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\ViewHelperNode->evaluate()
#25 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/AbstractNode.php(36): TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\AbstractNode->evaluateChildNode()
#26 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/Parser/SyntaxTree/RootNode.php(25): TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\AbstractNode->evaluateChildNodes()
#27 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/Parser/ParsingState.php(119): TYPO3Fluid\\Fluid\\Core\\Parser\\SyntaxTree\\RootNode->evaluate()
#28 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php(201): TYPO3Fluid\\Fluid\\Core\\Parser\\ParsingState->render()
#29 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Mail/FluidEmail.php(207): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->render()
#30 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Mail/FluidEmail.php(187): TYPO3\\CMS\\Core\\Mail\\FluidEmail->renderContent()
#31 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Mail/FluidEmail.php(137): TYPO3\\CMS\\Core\\Mail\\FluidEmail->generateTemplatedBody()
#32 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/symfony/mailer/SentMessage.php(33): TYPO3\\CMS\\Core\\Mail\\FluidEmail->ensureValidity()
#33 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/symfony/mailer/Transport/AbstractTransport.php(70): Symfony\\Component\\Mailer\\SentMessage->__construct()
#34 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/symfony/mailer/Transport/SendmailTransport.php(77): Symfony\\Component\\Mailer\\Transport\\AbstractTransport->send()
#35 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Mail/Mailer.php(125): Symfony\\Component\\Mailer\\Transport\\SendmailTransport->send()
#36 /usr/www/users/juergezdy/typo3_104/cms/typo3conf/ext/form_consent/Classes/Domain/Finishers/ConsentFinisher.php(137): TYPO3\\CMS\\Core\\Mail\\Mailer->send()
#37 /usr/www/users/juergezdy/typo3_104/cms/typo3conf/ext/form_consent/Classes/Domain/Finishers/ConsentFinisher.php(93): EliasHaeussler\\Typo3FormConsent\\Domain\\Finishers\\ConsentFinisher->executeConsent()
#38 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/form/Classes/Domain/Finishers/AbstractFinisher.php(156): EliasHaeussler\\Typo3FormConsent\\Domain\\Finishers\\ConsentFinisher->executeInternal()
#39 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/form/Classes/Domain/Runtime/FormRuntime.php(720): TYPO3\\CMS\\Form\\Domain\\Finishers\\AbstractFinisher->execute()
#40 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/form/Classes/Domain/Runtime/FormRuntime.php(670): TYPO3\\CMS\\Form\\Domain\\Runtime\\FormRuntime->invokeFinishers()
#41 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/form/Classes/ViewHelpers/RenderViewHelper.php(118): TYPO3\\CMS\\Form\\Domain\\Runtime\\FormRuntime->render()
#42 /usr/www/users/juergezdy/typo3_104/cms/typo3temp/var/cache/code/fluid_template/FormFrontend_action_render_fa4dbff2c61af5320ac05889fe344d8d609ba7d7.php(66): TYPO3\\CMS\\Form\\ViewHelpers\\RenderViewHelper::renderStatic()
#43 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractConditionViewHelper.php(78): FormFrontend_action_render_fa4dbff2c61af5320ac05889fe344d8d609ba7d7->{closure}()
#44 /usr/www/users/juergezdy/typo3_104/cms/typo3temp/var/cache/code/fluid_template/FormFrontend_action_render_fa4dbff2c61af5320ac05889fe344d8d609ba7d7.php(103): TYPO3Fluid\\Fluid\\Core\\ViewHelper\\AbstractConditionViewHelper::renderStatic()
#45 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/vendor/typo3fluid/fluid/src/View/AbstractTemplateView.php(186): FormFrontend_action_render_fa4dbff2c61af5320ac05889fe344d8d609ba7d7->render()
#46 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php(1093): TYPO3Fluid\\Fluid\\View\\AbstractTemplateView->render()
#47 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/form/Classes/Controller/FormFrontendController.php(80): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\ActionController->htmlResponse()
#48 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php(575): TYPO3\\CMS\\Form\\Controller\\FormFrontendController->renderAction()
#49 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php(492): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\ActionController->callActionMethod()
#50 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/extbase/Classes/Mvc/Dispatcher.php(96): TYPO3\\CMS\\Extbase\\Mvc\\Controller\\ActionController->processRequest()
#51 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/extbase/Classes/Mvc/Web/FrontendRequestHandler.php(46): TYPO3\\CMS\\Extbase\\Mvc\\Dispatcher->dispatch()
#52 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/extbase/Classes/Core/Bootstrap.php(165): TYPO3\\CMS\\Extbase\\Mvc\\Web\\FrontendRequestHandler->handleRequest()
#53 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/extbase/Classes/Core/Bootstrap.php(148): TYPO3\\CMS\\Extbase\\Core\\Bootstrap->handleFrontendRequest()
#54 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(5381): TYPO3\\CMS\\Extbase\\Core\\Bootstrap->run()
#55 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/ContentObject/UserContentObject.php(44): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->callUserFunction()
#56 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(800): TYPO3\\CMS\\Frontend\\ContentObject\\UserContentObject->render()
#57 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php(736): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->render()
#58 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php(2824): TYPO3\\CMS\\Frontend\\ContentObject\\ContentObjectRenderer->cObjGetSingle()
#59 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php(2782): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->processNonCacheableContentPartsAndSubstituteContentMarkers()
#60 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/Controller/TypoScriptFrontendController.php(2751): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->recursivelyReplaceIntPlaceholdersInContent()
#61 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/Http/RequestHandler.php(165): TYPO3\\CMS\\Frontend\\Controller\\TypoScriptFrontendController->INTincScript()
#62 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Middleware/ResponsePropagation.php(34): TYPO3\\CMS\\Frontend\\Http\\RequestHandler->handle()
#63 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Core\\Middleware\\ResponsePropagation->process()
#64 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/Middleware/OutputCompression.php(48): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#65 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\OutputCompression->process()
#66 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/adminpanel/Classes/Middleware/AdminPanelDataPersister.php(44): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#67 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Adminpanel\\Middleware\\AdminPanelDataPersister->process()
#68 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/adminpanel/Classes/Middleware/AdminPanelRenderer.php(46): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#69 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Adminpanel\\Middleware\\AdminPanelRenderer->process()
#70 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/Middleware/ContentLengthResponseHeader.php(46): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#71 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\ContentLengthResponseHeader->process()
#72 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/Middleware/ShortcutAndMountPointRedirect.php(79): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#73 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\ShortcutAndMountPointRedirect->process()
#74 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/Middleware/PrepareTypoScriptFrontendRendering.php(78): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#75 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\PrepareTypoScriptFrontendRendering->process()
#76 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/Middleware/TypoScriptFrontendInitialization.php(104): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#77 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\TypoScriptFrontendInitialization->process()
#78 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/Middleware/PageArgumentValidator.php(132): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#79 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\PageArgumentValidator->process()
#80 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/Middleware/PreviewSimulator.php(66): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#81 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\PreviewSimulator->process()
#82 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/adminpanel/Classes/Middleware/SqlLogging.php(58): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#83 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Adminpanel\\Middleware\\SqlLogging->process()
#84 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/Middleware/PageResolver.php(106): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#85 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\PageResolver->process()
#86 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/Middleware/StaticRouteResolver.php(80): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#87 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\StaticRouteResolver->process()
#88 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/Middleware/SiteBaseRedirectResolver.php(94): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#89 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\SiteBaseRedirectResolver->process()
#90 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/redirects/Classes/Http/Middleware/RedirectHandler.php(84): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#91 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Redirects\\Http\\Middleware\\RedirectHandler->process()
#92 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/adminpanel/Classes/Middleware/AdminPanelInitiator.php(55): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#93 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Adminpanel\\Middleware\\AdminPanelInitiator->process()
#94 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/Middleware/FrontendUserAuthenticator.php(91): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#95 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\FrontendUserAuthenticator->process()
#96 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/Middleware/BackendUserAuthenticator.php(78): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#97 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\BackendUserAuthenticator->process()
#98 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/Middleware/MaintenanceMode.php(55): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#99 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\MaintenanceMode->process()
#100 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/Middleware/SiteResolver.php(65): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#101 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\SiteResolver->process()
#102 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/Middleware/EidHandler.php(64): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#103 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\EidHandler->process()
#104 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Middleware/NormalizedParamsAttribute.php(45): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#105 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Core\\Middleware\\NormalizedParamsAttribute->process()
#106 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Middleware/VerifyHostHeader.php(55): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#107 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Core\\Middleware\\VerifyHostHeader->process()
#108 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/Middleware/TimeTrackerInitialization.php(58): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#109 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(172): TYPO3\\CMS\\Frontend\\Middleware\\TimeTrackerInitialization->process()
#110 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/MiddlewareDispatcher.php(78): Psr\\Http\\Server\\RequestHandlerInterface@anonymous->handle()
#111 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/AbstractApplication.php(86): TYPO3\\CMS\\Core\\Http\\MiddlewareDispatcher->handle()
#112 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/frontend/Classes/Http/Application.php(69): TYPO3\\CMS\\Core\\Http\\AbstractApplication->handle()
#113 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/typo3/sysext/core/Classes/Http/AbstractApplication.php(100): TYPO3\\CMS\\Frontend\\Http\\Application->handle()
#114 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/index.php(20): TYPO3\\CMS\\Core\\Http\\AbstractApplication->run()
#115 /usr/www/users/juergezdy/typo3_104/typo3_src-11.5.10/index.php(21): {closure}()
#116 {main}","code":"20220513140713fd1b26ad"}
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by eliashaeussler** [comment]
Hi @zzzooorrrx, does your problem still exist?

**Comment by eliashaeussler** [comment]
I'm closing this issue now due to lack of response.
